In [1]:
#sınıflandırma problemi
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


In [2]:
df=pd.read_csv(r"C:\Users\Lenovo\Veri-Analizi-2\Projeler-ders\datasets\churn.csv")

In [36]:
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [4]:
 # müşterinin bankadan çıkması ile ilgili olmayanları tablodan çıkarıcaz

In [5]:
df= df.drop(columns=["RowNumber","CustomerId","Surname"])

In [6]:
df.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [7]:
# kategorisel verileri nümeriğe çevirmek lazım

In [9]:
df=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)

In [10]:
y=df["Exited"]
x=df.drop("Exited",axis=1)

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=61,train_size=0.7)

In [13]:
rf=RandomForestClassifier()
model= rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.8603333333333333

In [14]:
model.predict([[500,22,4,0,5,1,1,20000,False,False,False]])

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
df2=pd.DataFrame()

In [19]:
df2["takim"]=["BJK","FB","GS","TS","MIY"]

In [21]:
pd.get_dummies(df2,columns=["takim"])

takim_BJK  takim_FB  takim_GS  takim_MIY  takim_TS
0          1         0         0          0         0
1          0         1         0          0         0
2          0         0         1          0         0
3          0         0         0          0         1
4          0         0         0          1         0

In [17]:
ohe=OneHotEncoder()

In [26]:
x= ohe.fit_transform(df2[["takim"]])

In [27]:
x.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [29]:
ohe.transform([["FB"]]).toarray()

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1., 0., 0., 0.]])

In [30]:
# -----------------------------

In [33]:
df.head(2)

CreditScore  Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0          619   42       2      0.00              1          1   
1          608   41       1  83807.86              1          0   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0